### ISSUE TITLE
Doesn't grab new password on reset

### ISSUE THREAD

**Issue by Sc00bz** [google/password-alert#19]
It only updates the password on successful log in.

**Comment by adhintz** [comment]
I agree -- we should also update on password changes. Thanks for the report!

**Comment by adhintz** [comment]
The main password change page is now handled by #46
However there's another change password for Google for Work users that @blueandgold is looking into as well.

We're also talking with the people that run the password change page. We'll try to get a better way to select the relevant HTML elements instead of relying on brittle CSS selectors for the email address and Change Password button.

**Comment by adhintz** [comment]
The other GfW password change page is now handled by #51

Closing for now, please feel free to reopen if you see any issues with it or there are any password change pages we missed.

Thanks @blueandgold for writing the code!
