### ISSUE TITLE
Alert pop up when signing in with someone else's Gmail account

### ISSUE THREAD

**Issue by martinezgjuan** [google/password-alert#85]
I logged in recently in a website in my computer with my sisters account and when I entered her credentials I received the Password Alert por up because her credentials for that website were the same as the ones for her Gmail account. The strange thing is that this happened while I was logged in with my chrome account.

By trying to login in some other website I became aware that this was her gmail password and I guess this was not meant to happen. It seems to me that this could be exploited to obtain passwords by not even attempting directly to login in Gmail.

Best regards,
Juan

**Comment by jkosslyn** [comment]
Thanks for the report, Juan. Question for you: did your sister previously log into her Gmail account while Chrome was signed into your profile?

**Comment by martinezgjuan** [comment]
Yes, she logged in in my computer a few months ago while Chrome was signed into my profile.

**Comment by jkosslyn** [comment]
So that's what happened: Password Alert was installed on your profile, so when her password was typed on accounts.google.com while your profile was active, Password Alert started protecting her password. Later, when you entered her password on a shopping site, you got an alert. The security risk here is extremely low, because this scenario only happens when (1) she typed in her password while logged into your Chrome profile, and (2) someone else subsequently typed in her password while also logged into the same Chrome profile. Furthermore, if you were malicious, this would all be moot because you would have been able to install a Chrome extension in your profile that would have captured her password immediately when she typed it in. The bottom line is that the safest thing is to avoid entering your password while signed into someone else's Chrome profile.

**Comment by martinezgjuan** [comment]
Ok, thank makes sense.
Thanks for the quick reply!
